version: "3.1"

services:
  reverse_proxy:
    build: 
      context: ./reverse_proxy
    image: shop-proxy

  database:
    build: 
       context: ./database
    image: shop-db

  appserver:
    build:
       context: app
    image: shop-app