apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-app-deployment
  labels:
{{ include "atsea.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "atsea.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      role: shop-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "atsea.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        role: shop-app
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: shop-app
          image: "{{ .Values.image.repository }}shop-app:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: tcp5005
              containerPort: 5005
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: appserver
  labels:
{{ include "atsea.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 5005
      targetPort: 5005
      protocol: TCP
      name: tcp5005
  selector:
    app.kubernetes.io/name: {{ include "atsea.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    role: shop-app