apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-db-deployment
  labels:
{{ include "atsea.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "atsea.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      role: shop-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "atsea.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        role: shop-db
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}shop-db:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp5432
              containerPort: 5432
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
{{ include "atsea.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "atsea.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    role: shop-db

